name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup
        uses: the-guild-org/shared-config/setup@v1
        with:
          node-version-file: .node-version

      - name: Install Dependencies
        run: yarn

      - name: Build Packages
        run: yarn build

      - name: "Test Packages"
        run: yarn test

      - name: "Test ESM & CJS integrity"
        run: yarn bob check
